(window.webpackJsonp=window.webpackJsonp||[]).push([[185],{698:function(r,e,t){"use strict";t.r(e);var a=t(6),n=Object(a.a)({},(function(){var r=this,e=r.$createElement,t=r._self._c||e;return t("ContentSlotsDistributor",{attrs:{"slot-key":r.$parent.slotKey}},[t("h1",{attrs:{id:"try-catch-不能捕获的错误有哪些"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#try-catch-不能捕获的错误有哪些"}},[r._v("#")]),r._v(" "),t("a",{attrs:{href:"https://segmentfault.com/a/1190000039813200",target:"_blank",rel:"noopener noreferrer"}},[r._v("try..catch 不能捕获的错误有哪些"),t("OutboundLink")],1)]),r._v(" "),t("p",[r._v("今天的内容中，我们来学习一下使用"),t("code",[r._v("try")]),r._v("、"),t("code",[r._v("catch")]),r._v("、"),t("code",[r._v("finally")]),r._v("和"),t("code",[r._v("throw")]),r._v("进行错误处理。我们还会讲一下 JS 中内置的错误对象("),t("code",[r._v("Error")]),r._v(", "),t("code",[r._v("SyntaxError")]),r._v(", "),t("code",[r._v("ReferenceError")]),r._v("等)以及如何定义自定义错误。")]),r._v(" "),t("h2",{attrs:{id:"_1-使用-try-catch-finally-throw"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-使用-try-catch-finally-throw"}},[r._v("#")]),r._v(" 1.使用 try..catch..finally..throw")]),r._v(" "),t("p",[r._v("在 JS 中处理错误，我们主要使用"),t("code",[r._v("try")]),r._v("、"),t("code",[r._v("catch")]),r._v("、"),t("code",[r._v("finally")]),r._v("和"),t("code",[r._v("throw")]),r._v("关键字。")]),r._v(" "),t("ul",[t("li",[t("code",[r._v("try")]),r._v("块包含我们需要检查的代码")]),r._v(" "),t("li",[r._v("关键字"),t("code",[r._v("throw")]),r._v("用于抛出自定义错误")]),r._v(" "),t("li",[t("code",[r._v("catch")]),r._v("块处理捕获的错误")]),r._v(" "),t("li",[t("code",[r._v("finally")]),r._v(" 块是最终结果无论如何，都会执行的一个块，可以在这个块里面做一些需要善后的事情")])]),r._v(" "),t("h4",{attrs:{id:"_1-1-try"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-1-try"}},[r._v("#")]),r._v(" 1.1 "),t("code",[r._v("try")])]),r._v(" "),t("p",[r._v("每个"),t("code",[r._v("try")]),r._v("块必须与至少一个"),t("code",[r._v("catch")]),r._v("或"),t("code",[r._v("finally")]),r._v("块，否则会抛出"),t("code",[r._v("SyntaxError")]),r._v("错误。")]),r._v(" "),t("p",[r._v("我们单独使用"),t("code",[r._v("try")]),r._v("块进行验证：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("try {\n  throw new Error('Error while executing the code');\n}\nⓧ Uncaught SyntaxError: Missing catch or finally after try\n")])])]),t("h4",{attrs:{id:"_1-2-try-catch"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-2-try-catch"}},[r._v("#")]),r._v(" 1.2 "),t("code",[r._v("try..catch")])]),r._v(" "),t("p",[r._v("建议将"),t("code",[r._v("try")]),r._v("与"),t("code",[r._v("catch")]),r._v("块一起使用，它可以优雅地处理"),t("code",[r._v("try")]),r._v("块抛出的错误。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("try {\n  throw new Error('Error while executing the code');\n} catch (err) {\n  console.error(err.message);\n}\n➤ ⓧ Error while executing the code\n")])])]),t("h4",{attrs:{id:"_1-2-1-try-catch-与-无效代码"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-2-1-try-catch-与-无效代码"}},[r._v("#")]),r._v(" 1.2.1 "),t("code",[r._v("try..catch")]),r._v(" 与 无效代码")]),r._v(" "),t("p",[t("code",[r._v("try..catch")]),r._v(" 无法捕获无效的 JS 代码，例如"),t("code",[r._v("try")]),r._v("块中的以下代码在语法上是错误的，但它不会被"),t("code",[r._v("catch")]),r._v("块捕获。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('try {\n  ~!$%^&*\n} catch(err) {\n  console.log("这里不会被执行");\n}\n➤ ⓧ Uncaught SyntaxError: Invalid or unexpected token\n')])])]),t("h4",{attrs:{id:"_1-2-2-try-catch-与-异步代码"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-2-2-try-catch-与-异步代码"}},[r._v("#")]),r._v(" 1.2.2 "),t("code",[r._v("try..catch")]),r._v(" 与 异步代码")]),r._v(" "),t("p",[r._v("同样，"),t("code",[r._v("try..catch")]),r._v("无法捕获在异步代码中引发的异常，例如"),t("code",[r._v("setTimeout")]),r._v("：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('try {\n  setTimeout(function() {\n    noSuchVariable;   // undefined variable\n  }, 1000);\n} catch (err) {\n  console.log("这里不会被执行");\n}\n')])])]),t("p",[r._v("未捕获的"),t("code",[r._v("ReferenceError")]),r._v("将在1秒后引发:")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("➤ ⓧ Uncaught ReferenceError: noSuchVariable is not defined\n")])])]),t("p",[r._v("所以 ，我们应该在异步代码内部使用 "),t("code",[r._v("try..catch")]),r._v(" 来处理错误：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('setTimeout(function() {\n  try {\n    noSuchVariable;\n  } catch(err) {\n    console.log("error is caught here!");\n  }\n}, 1000);\n')])])]),t("h4",{attrs:{id:"_1-2-3-嵌套-try-catch"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-2-3-嵌套-try-catch"}},[r._v("#")]),r._v(" 1.2.3 嵌套 "),t("code",[r._v("try..catch")])]),r._v(" "),t("p",[r._v("我们还可以使用嵌套的"),t("code",[r._v("try")]),r._v("和"),t("code",[r._v("catch")]),r._v("块向上抛出错误，如下所示：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("try {\n  try {\n    throw new Error('Error while executing the inner code');\n  } catch (err) {\n    throw err;\n  }\n} catch (err) {\n  console.log(\"Error caught by outer block:\");\n  console.error(err.message);\n}\nError caught by outer block:\n➤ ⓧ Error while executing the code\n")])])]),t("h4",{attrs:{id:"_1-3-try-finally"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-3-try-finally"}},[r._v("#")]),r._v(" 1.3 "),t("code",[r._v("try..finally")])]),r._v(" "),t("p",[r._v("不建议仅使用 "),t("code",[r._v("try..finally")]),r._v(" 而没有 "),t("code",[r._v("catch")]),r._v(" 块，看看下面会发生什么：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("try {\n  throw new Error('Error while executing the code');\n} finally {\n  console.log('finally');\n}\nfinally\n➤ ⓧ Uncaught Error: Error while executing the code\n")])])]),t("p",[r._v("这里注意两件事：")]),r._v(" "),t("ul",[t("li",[r._v("即使从"),t("code",[r._v("try")]),r._v("块抛出错误后，也会执行"),t("code",[r._v("finally")]),r._v("块")]),r._v(" "),t("li",[r._v("如果没有"),t("code",[r._v("catch")]),r._v("块，错误将不能被优雅地处理，从而导致未捕获的错误")])]),r._v(" "),t("h4",{attrs:{id:"_1-4-try-catch-finally"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-4-try-catch-finally"}},[r._v("#")]),r._v(" 1.4 "),t("code",[r._v("try..catch..finally")])]),r._v(" "),t("p",[r._v("建议使用"),t("code",[r._v("try...catch")]),r._v("块和可选的"),t("code",[r._v("finally")]),r._v("块。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('try {\n  console.log("Start of try block");\n  throw new Error(\'Error while executing the code\');\n  console.log("End of try block -- never reached");\n} catch (err) {\n  console.error(err.message);\n} finally {\n  console.log(\'Finally block always run\');\n}\nconsole.log("Code execution outside try-catch-finally block continue..");\nStart of try block\n➤ ⓧ Error while executing the code\nFinally block always run\nCode execution outside try-catch-finally block continue..\n')])])]),t("p",[r._v("这里还要注意两件事：")]),r._v(" "),t("ul",[t("li",[r._v("在"),t("code",[r._v("try")]),r._v("块中抛出错误后往后的代码不会被执行了")]),r._v(" "),t("li",[r._v("即使在"),t("code",[r._v("try")]),r._v("块抛出错误之后，"),t("code",[r._v("finally")]),r._v("块仍然执行")])]),r._v(" "),t("p",[t("code",[r._v("finally")]),r._v("块通常用于清理资源或关闭流，如下所示：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("try {\n  openFile(file);\n  readFile(file);\n} catch (err) {\n  console.error(err.message);\n} finally {\n  closeFile(file);\n}\n")])])]),t("h4",{attrs:{id:"_1-5-throw"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_1-5-throw"}},[r._v("#")]),r._v(" 1.5 "),t("code",[r._v("throw")])]),r._v(" "),t("p",[t("code",[r._v("throw")]),r._v("语句用于引发异常。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("throw <expression>\n// throw primitives and functions\nthrow \"Error404\";\nthrow 42;\nthrow true;\nthrow {toString: function() { return \"I'm an object!\"; } };\n\n// throw error object\nthrow new Error('Error while executing the code');\nthrow new SyntaxError('Something is wrong with the syntax');\nthrow new ReferenceError('Oops..Wrong reference');\n\n// throw custom error object\nfunction ValidationError(message) {\n  this.message = message;\n  this.name = 'ValidationError';\n}\nthrow new ValidationError('Value too high');\n")])])]),t("h2",{attrs:{id:"_2-异步代码中的错误处理"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_2-异步代码中的错误处理"}},[r._v("#")]),r._v(" 2. 异步代码中的错误处理")]),r._v(" "),t("p",[r._v("对于异步代码的错误处理可以"),t("code",[r._v("Promise")]),r._v("和"),t("code",[r._v("async await")]),r._v("。")]),r._v(" "),t("h4",{attrs:{id:"_2-1-promise-中的-then-catch"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_2-1-promise-中的-then-catch"}},[r._v("#")]),r._v(" 2.1 Promise 中的 "),t("code",[r._v("then..catch")])]),r._v(" "),t("p",[r._v("我们可以使用"),t("code",[r._v("then()")]),r._v("和"),t("code",[r._v("catch()")]),r._v("链接多个 Promises，以处理链中单个 Promise 的错误，如下所示：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("Promise.resolve(1)\n  .then(res => {\n      console.log(res);  // 打印 '1'\n\n      throw new Error('something went wrong');  // throw error\n\n      return Promise.resolve(2);  // 这里不会被执行\n  })\n  .then(res => {\n      // 这里也不会执行，因为错误还没有被处理\n      console.log(res);    \n  })\n  .catch(err => {\n      console.error(err.message);  // 打印 'something went wrong'\n      return Promise.resolve(3);\n  })\n  .then(res => {\n      console.log(res);  // 打印 '3'\n  })\n  .catch(err => {\n      // 这里不会被执行\n      console.error(err);\n  })\n")])])]),t("p",[r._v("我们来看一个更实际的示例，其中我们使用"),t("code",[r._v("fetch")]),r._v("调用API，该 API 返回一个"),t("code",[r._v("promise")]),r._v("对象，我们使用"),t("code",[r._v("catch")]),r._v("块优雅地处理 API 失败。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('function handleErrors(response) {\n    if (!response.ok) {\n        throw Error(response.statusText);\n    }\n    return response;\n}\n\nfetch("http://httpstat.us/500")\n    .then(handleErrors)\n    .then(response => console.log("ok"))\n    .catch(error => console.log("Caught", error));\nCaught Error: Internal Server Error\n    at handleErrors (<anonymous>:3:15)\n')])])]),t("h4",{attrs:{id:"_2-2-try-catch-和-async-await"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_2-2-try-catch-和-async-await"}},[r._v("#")]),r._v(" 2.2 "),t("code",[r._v("try..catch")]),r._v(" 和 "),t("code",[r._v("async await")])]),r._v(" "),t("p",[r._v("在 "),t("code",[r._v("async await")]),r._v(" 中 使用"),t("code",[r._v("try..catch")]),r._v(" 比较容易：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('(async function() {\n    try {\n        await fetch("http://httpstat.us/500");\n    } catch (err) {\n        console.error(err.message);\n    }\n})();\n')])])]),t("p",[r._v("让我们看同一示例，其中我们使用"),t("code",[r._v("fetch")]),r._v("调用API，该API返回一个"),t("code",[r._v("promise")]),r._v("对象， 我们使用"),t("code",[r._v("try..catch")]),r._v("块优雅地处理API失败。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('function handleErrors(response) {\n    if (!response.ok) {\n        throw Error(response.statusText);\n    }\n}\n\n(async function() {\n    try {\n      let response = await fetch("http://httpstat.us/500");\n      handleErrors(response);\n      let data = await response.json();\n      return data;\n    } catch (error) {\n        console.log("Caught", error)\n    }\n})();\nCaught Error: Internal Server Error\n    at handleErrors (<anonymous>:3:15)\n    at <anonymous>:11:7\n')])])]),t("h2",{attrs:{id:"_3-js-中的内置错误"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-js-中的内置错误"}},[r._v("#")]),r._v(" 3. JS 中的内置错误")]),r._v(" "),t("h4",{attrs:{id:"_3-1-error"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-1-error"}},[r._v("#")]),r._v(" 3.1 Error")]),r._v(" "),t("p",[r._v("JavaScript 有内置的错误对象，它通常由"),t("code",[r._v("try")]),r._v("块抛出，并在"),t("code",[r._v("catch")]),r._v("块中捕获，"),t("strong",[r._v("Error")]),r._v(" 对象包含以下属性：")]),r._v(" "),t("ul",[t("li",[t("strong",[r._v("name")]),r._v("：是错误的名称，例如 “Error”, “SyntaxError”, “ReferenceError” 等。")]),r._v(" "),t("li",[t("strong",[r._v("message")]),r._v("：有关错误详细信息的消息。")]),r._v(" "),t("li",[t("strong",[r._v("stack")]),r._v("：是用于调试目的的错误的堆栈跟踪。")])]),r._v(" "),t("p",[r._v("我们创建一个"),t("strong",[r._v("Error")]),r._v(" 对象，并查看它的名称和消息属性:")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('const err = new Error(\'Error while executing the code\');\n\nconsole.log("name:", err.name);\nconsole.log("message:", err.message);\nconsole.log("stack:", err.stack);\nname: Error\nmessage: Error while executing the code\nstack: Error: Error while executing the code\n    at <anonymous>:1:13\n')])])]),t("p",[r._v("JavaScript 有以下内置错误，这些错误是从 "),t("strong",[r._v("Error")]),r._v(" 对象继承而来的")]),r._v(" "),t("h4",{attrs:{id:"_3-2-evalerror"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-2-evalerror"}},[r._v("#")]),r._v(" 3.2 EvalError")]),r._v(" "),t("p",[t("strong",[r._v("EvalError")]),r._v(" 表示关于全局"),t("code",[r._v("eval()")]),r._v("函数的错误，这个异常不再由 JS 抛出，它的存在是为了向后兼容。")]),r._v(" "),t("h4",{attrs:{id:"_3-3-rangeerror"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-3-rangeerror"}},[r._v("#")]),r._v(" 3.3 RangeError")]),r._v(" "),t("p",[r._v("当值超出范围时，将引发"),t("code",[r._v("RangeError")]),r._v("。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("➤ [].length = -1\nⓧ Uncaught RangeError: Invalid array length\n")])])]),t("h4",{attrs:{id:"_3-4-referenceerror"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-4-referenceerror"}},[r._v("#")]),r._v(" 3.4 ReferenceError")]),r._v(" "),t("p",[r._v("当引用一个不存在的变量时，将引发 "),t("strong",[r._v("ReferenceError")]),r._v("。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("➤ x = x + 1;\nⓧ Uncaught ReferenceError: x is not defined\n")])])]),t("h4",{attrs:{id:"_3-5-syntaxerror"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-5-syntaxerror"}},[r._v("#")]),r._v(" 3.5 SyntaxError")]),r._v(" "),t("p",[r._v("当你在 JS 代码中使用任何错误的语法时，都会引发"),t("code",[r._v("SyntaxError")]),r._v("。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("➤ function() { return 'Hi!' }\nⓧ Uncaught SyntaxError: Function statements require a function name\n\n➤ 1 = 1\nⓧ Uncaught SyntaxError: Invalid left-hand side in assignment\n\n➤ JSON.parse(\"{ x }\");\nⓧ Uncaught SyntaxError: Unexpected token x in JSON at position 2\n")])])]),t("h4",{attrs:{id:"_3-6-typeerror"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-6-typeerror"}},[r._v("#")]),r._v(" 3.6 TypeError")]),r._v(" "),t("p",[r._v("如果该值不是预期的类型，则抛出"),t("code",[r._v("TypeError")]),r._v("。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("➤ 1();\nⓧ Uncaught TypeError: 1 is not a function\n\n➤ null.name;\nⓧ Uncaught TypeError: Cannot read property 'name' of null\n")])])]),t("h4",{attrs:{id:"_3-7-urierror"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_3-7-urierror"}},[r._v("#")]),r._v(" 3.7 URIError")]),r._v(" "),t("p",[r._v("如果以错误的方式使用全局 URI 方法，则会抛出"),t("code",[r._v("URIError")]),r._v("。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('➤ decodeURI("%%%");\nⓧ Uncaught URIError: URI malformed\n')])])]),t("h2",{attrs:{id:"_4-定义并抛出自定义错误"}},[t("a",{staticClass:"header-anchor",attrs:{href:"#_4-定义并抛出自定义错误"}},[r._v("#")]),r._v(" 4. 定义并抛出自定义错误")]),r._v(" "),t("p",[r._v("我们也可以用这种方式定义自定义错误。")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('class CustomError extends Error {\n  constructor(message) {\n    super(message);\n    this.name = "CustomError";\n  } \n};\n\nconst err = new CustomError(\'Custom error while executing the code\');\n\nconsole.log("name:", err.name);\nconsole.log("message:", err.message);\nname: CustomError\nmessage: Custom error while executing the code\n')])])]),t("p",[r._v("我们还可以进一步增强"),t("code",[r._v("CustomError")]),r._v("对象以包含错误代码")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v('class CustomError extends Error {\n  constructor(message, code) {\n    super(message);\n    this.name = "CustomError";\n    this.code = code;\n  } \n};\n\nconst err = new CustomError(\'Custom error while executing the code\', "ERROR_CODE");\n\nconsole.log("name:", err.name);\nconsole.log("message:", err.message);\nconsole.log("code:", err.code);\nname: CustomError\nmessage: Custom error while executing the code\ncode: ERROR_CODE\n')])])]),t("p",[r._v("在"),t("code",[r._v("try..catch")]),r._v("块中使用它：")]),r._v(" "),t("div",{staticClass:"language- extra-class"},[t("pre",{pre:!0,attrs:{class:"language-text"}},[t("code",[r._v("try{\n  try {\n    null.name;\n  }catch(err){\n    throw new CustomError(err.message, err.name);  //message, code\n  }\n}catch(err){\n  console.log(err.name, err.code, err.message);\n}\n")])])]),t("blockquote",[t("p",[r._v("CustomError TypeError Cannot read property 'name' of null")])])])}),[],!1,null,null,null);e.default=n.exports}}]);